language: node_js
branches:
  only:
    - build-dev
node_js: '11.1'
cache:
  - yarn
  - npm
deploy:
  skip_cleanup: true
  provider: script
  script: yarn compile
  on:
    branch: build-dev
after_deploy:
  - git add bin/
  - git commit -m "Travis build: $TRAVIS_BUILD_NUMBER"
  - git remote add origin-pages https://${GH_TOKEN}@github.com/havasmtl-jkahner/botpress-channel-web.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin-pages build-dev
